version: "3.9"

# Differences atop of production environment

services:
    api:
        environment:
            NODE_ENV: development
        command: sh -c "npx rollup -c -w"

    mysql:
        ports:
            - "3306:3306"

    redis-commander:
        container_name: artic.redis-commander
        image: rediscommander/redis-commander:latest
        ports:
            - "8081:8081"
        env_file:
            - .env
        depends_on:
            - redis
        networks:
            - artic
