version: "3.9"

# Extension of production environment

services:
  api:
    environment:
      - NODE_ENV=development
      - MYSQL_PASSWORD=dev
    command: sh -c "npm i && npx rollup -c -w"

  mysql:
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_PASSWORD=dev

volumes:
  mysql_data:
